//
// Created by Steve Wheeler on 08/01/2025.
//

#pragma once

// Systems
#include "AbilityFactory.hpp"
#include "Camera.hpp"
#include "Cursor.hpp"
#include "CursorClickIndicator.hpp"
#include "DialogFactory.hpp"
#include "FullscreenTextOverlayManager.hpp"
#include "GameUiEngine.hpp"
#include "ItemFactory.hpp"
#include "LightManager.hpp"
#include "LootTable.hpp"
#include "NpcManager.hpp"
#include "QuestManager.hpp"
#include "systems/ActorMovementSystem.hpp"
#include "systems/AnimationSystem.hpp"
#include "systems/CollisionSystem.hpp"
#include "systems/CombatSystem.hpp"
#include "systems/ContextualDialogSystem.hpp"
#include "systems/ControllableActorSystem.hpp"
#include "systems/DialogSystem.hpp"
#include "systems/DoorSystem.hpp"
#include "systems/EquipmentSystem.hpp"
#include "systems/HealthBarSystem.hpp"
#include "systems/InventorySystem.hpp"
#include "systems/LootSystem.hpp"
#include "systems/NavigationGridSystem.hpp"
#include "systems/PartySystem.hpp"
#include "systems/PlayerAbilitySystem.hpp"
#include "systems/RenderSystem.hpp"
#include "systems/SpatialAudioSystem.hpp"
#include "systems/states/StateMachines.hpp"
#include "systems/TimerSystem.hpp"
#include "systems/UberShaderSystem.hpp"
#include "UserInput.hpp"